archivo = open('Hola.txt', 'r')
text_ini = archivo.read()
archivo = open('Hola.txt', 'w')
archivo.close()
texto = input ("Ingrese el texto: ")
archivo = open('Hola.txt', 'w')
archivo.write(text_ini)
archivo.write("\n")
archivo.write(texto)
archivo.close()